var permissionData = [{
	value: '10',
	text: '系统设置管理',
	children: [{
		value: "1001",
		text: "修改公司"
	}, {
		value: "1002",
		text: "新增部门"
	}, {
		value: "1003",
		text: "删除部门"
	}, {
		value: "1004",
		text: "修改部门"
	}, {
		value: "1005",
		text: "修改职员"
	}, {
		value: "1006",
		text: "删除职员"
	}, {
		value: "1007",
		text: "职员权限"
	}, {
		value: "1008",
		text: "修改密码"
	}, {
		value: "1009",
		text: "参数设置"
	}, {
		value: "1010",
		text: "新增角色"
	}, {
		value: "1011",
		text: "修改角色"
	}, {
		value: "1012",
		text: "删除角色"
	}, {
		value: "1013",
		text: "新增备注"
	}, {
		value: "1015",
		text: "修改备注"
	}, {
		value: "1016",
		text: "删除备注"
	}]
}, {
	value: '11',
	text: '基础数据管理',
	children: [{
		value: "1101",
		text: "新增数据"
	}, {
	    value: "1102",
		text: "修改数据"
	}, {
	    value: "1103",
		text: "删除数据"
	}]
}, {
	value: '12',
	text: '邮件推广中心',
	children: [{
		value: "1201",
		text: "新增邮件地址"
	}, {
	    value: "1202",
		text: "上传邮件列表"
	}, {
	    value: "1203",
		text: "查看邮件列表"
	}, {
	    value: "1204",
		text: "删除邮件列表"
	}, {
	    value: "1205",
		text: "新增群组邮件列表"
	}, {
	    value: "1206",
		text: "修改群组邮件列表"
	}, {
	    value: "1207",
		text: "查看群组邮件列表"
	}, {
	    value: "1208",
		text: "删除群组邮件列表"
	}, {
	    value: "1209",
		text: "新增邮箱设置"
	}, {
	    value: "1210",
		text: "修改邮箱设置"
	}, {
	    value: "1211",
		text: "删除邮箱设置"
	}, {
	    value: "1212",
		text: "新增邮件内容"
	}, {
	    value: "1213",
		text: "修改邮件内容"
	}, {
	    value: "1214",
		text: "删除邮件内容"
	}, {
	    value: "1215",
		text: "查看邮件内容"
	}, {
	    value: "1216",
		text: "新增邮件推广配置"
	}, {
	    value: "1217",
		text: "删除邮件推广配置"
	}, {
	    value: "1218",
		text: "查看邮件推广详情"
	}, {
	    value: "1219",
		text: "查看邮件发送列表"
	}, {
	    value: "1220",
		text: "启动邮件发送列表"
	}, {
	    value: "1221",
		text: "重新发送邮件列表"
	}]
}, {
	value: '13',
	text: '财务管理中心',
	children: [{
		value: "1301",
		text: "查看费用清单"
	}, {
	    value: "1302",
		text: "新增费用清单"
	}, {
	    value: "1303",
		text: "修改费用清单"
	}, {
	    value: "1304",
		text: "删除费用清单"
	}, {
	    value: "1305",
		text: "查看费用清单详情"
	}, {
	    value: "1306",
		text: "查看汇率"
	}, {
	    value: "1307",
		text: "新增汇率"
	}, {
	    value: "1308",
		text: "修改汇率"
	}, {
	    value: "1309",
		text: "删除汇率"
	}, {
	    value: "1310",
		text: "查看费用管理-账单列表"
	}, {
	    value: "1311",
		text: "查看费用管理-账单详情"
	}, {
	    value: "1312",
		text: "查看费用管理-删除账单"
	}, {
	    value: "1313",
		text: "查看费用管理-发送账单"
	}, {
	    value: "1314",
		text: "查看费用管理-账单收款"
	}, {
	    value: "1315",
		text: "查看费用管理-发票列表"
	}, {
	    value: "1316",
		text: "查看费用管理-发票详情"
	}, {
	    value: "1317",
		text: "查看费用管理-删除发票"
	}, {
	    value: "1318",
		text: "查看费用管理-付款列表"
	}, {
	    value: "1319",
		text: "查看费用管理-删除付款"
	}, {
	    value: "1320",
		text: "查看费用管理-收款列表"
	}, {
	    value: "1321",
		text: "查看费用管理-删除收款"
	}, {
	    value: "1322",
		text: "查看应收报表"
	}, {
	    value: "1323",
		text: "打印应收报表"
	}, {
	    value: "1324",
		text: "查看应付报表"
	}, {
	    value: "1325",
		text: "打印应付报表"
	}, {
	    value: "1326",
		text: "查看对账通知单"
	}, {
	    value: "1327",
		text: "打印对账通知单"
	}]
}, {
	value: '14',
	text: '运价管理中心',
	children: [{
		value: "1401",
		text: "查看运价列表"
	}, {
	    value: "1402",
		text: "新增运价"
	}, {
	    value: "1403",
		text: "上传运价列表"
	}, {
	    value: "1404",
		text: "删除运价"
	}, {
	    value: "1405",
		text: "新增报价单"
	}, {
	    value: "1406",
		text: "复制运价"
	}, {
	    value: "1407",
		text: "查看当地费用列表"
	}, {
	    value: "1408",
		text: "新增当地费用"
	}, {
	    value: "1409",
		text: "上传当地费用列表"
	}, {
	    value: "1410",
		text: "删除当地费用"
	}, {
	    value: "1411",
		text: "查看当地费用详情"
	}, {
	    value: "1412",
		text: "修改当地费用详情"
	}, {
	    value: "1413",
		text: "复制当地费用详情"
	}, {
	    value: "1414",
		text: "查看拖箱费用"
	}, {
	    value: "1415",
		text: "新增拖箱费用"
	}, {
	    value: "1416",
		text: "上传拖箱费用"
	}, {
	    value: "1417",
		text: "修改拖箱费用"
	}, {
	    value: "1418",
		text: "删除拖箱费用"
	}, {
	    value: "1419",
		text: "复制拖箱费用"
	}]
}, {
	value: '15',
	text: '询盘管理中心',
	children: [{
		value: "1501",
		text: "新增询盘"
	}, {
	    value: "1502",
		text: "查看内部询盘"
	}, {
	    value: "1503",
		text: "内部询盘-分配"
	}, {
	    value: "1504",
		text: "内部询盘-回收"
	}, {
	    value: "1505",
		text: "内部询盘-关闭"
	}, {
	    value: "1506",
		text: "查看外部询盘"
	}, {
	    value: "1507",
		text: "外部询盘-分配"
	}, {
	    value: "1508",
		text: "外部询盘-回收"
	}, {
	    value: "1509",
		text: "外部询盘-关闭"
	}]
}, {
	value: '16',
	text: '客户管理中心',
	children: [{
		value: "1601",
		text: "查看客户列表"
	}, {
	    value: "1602",
		text: "新增客户"
	}, {
	    value: "1603",
		text: "修改客户"
	}, {
	    value: "1604",
		text: "新增联系人"
	}, {
	    value: "1605",
		text: "发送账号邮件"
	}, {
	    value: "1606",
		text: "查看客户详情"
	}, {
	    value: "1607",
		text: "新增客户跟进"
	}, {
	    value: "1608",
		text: "修改客户跟进"
	}, {
	    value: "1609",
		text: "删除客户跟进"
	}, {
	    value: "1610",
		text: "新增客户需求"
	}, {
	    value: "1611",
		text: "修改客户需求"
	}, {
	    value: "1612",
		text: "删除客户需求"
	}, {
	    value: "1613",
		text: "新增提单信息"
	}, {
	    value: "1614",
		text: "修改提单信息"
	}, {
	    value: "1615",
		text: "删除提单信息"
	}, {
	    value: "1616",
		text: "新增联系公司"
	}, {
	    value: "1617",
		text: "设置主要联系人"
	}]
}, {
	value: '17',
	text: '货物管理中心',
	children: [{
		value: "1701",
		text: "查看订单列表"
	}, {
	    value: "1702",
		text: "新增订单"
	}, {
	    value: "1703",
		text: "订单详情"
	}, {
	    value: "1704",
		text: "修改订单"
	}, {
	    value: "1705",
		text: "锁定订单"
	}, {
	    value: "1706",
		text: "解锁订单"
	}, {
	    value: "1707",
		text: "复制订单"
	}, {
	    value: "1708",
		text: "打印订单"
	}, {
	    value: "1709",
		text: "上传订单文件"
	}, {
	    value: "1710",
		text: "查看订单文件"
	}, {
	    value: "1711",
		text: "删除订单文件"
	}, {
	    value: "1712",
		text: "新增货代单"
	}, {
	    value: "1713",
		text: "查看订舱列表"
	}, {
	    value: "1714",
		text: "确认订舱"
	}, {
	    value: "1715",
		text: "取消订舱"
	}, {
	    value: "1716",
		text: "新增联系单"
	}, {
	    value: "1717",
		text: "查看打印模板"
	}, {
	    value: "1718",
		text: "新增打印模板"
	}, {
	    value: "1719",
		text: "修改打印模板"
	}, {
	    value: "1720",
		text: "删除打印模板"
	}, {
	    value: "1721",
		text: "查看利润报表"
	}, {
	    value: "1722",
		text: "打印利润报表"
	}]
}]